apiVersion: v1
kind: Namespace
metadata:
  name: kuma
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pvc
  namespace: kuma
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
  namespace: kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma
  template:
    metadata:
      labels:
        app: kuma
    spec:
      containers:
      - name: kuma
        image: louislam/uptime-kuma:1
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: kuma-data
          mountPath: /app/data
      volumes:
      - name: kuma-data
        persistentVolumeClaim:
          claimName: kuma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kuma
  namespace: kuma
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: kuma
