---
- name: NanoPI Cluster
  hosts: nodes
  remote_user: dietpi
  become: yes
  gather_facts: yes
  tasks:
    - name: Disable root login by changing shell
      user:
        name: root
        shell: /usr/sbin/nologin

    - name: Update DietPi
      command: /boot/dietpi/dietpi-update

    - name: Install snapd with apt
      apt:
        name: snapd
        state: present

    - name: Ensure snapd service is running
      service:
        name: snapd
        state: started
        enabled: yes

    - name: Install MicroK8s
      command: snap install microk8s --classic
      args:
        creates: /snap/bin/microk8s

    - name: Add the current user to the microk8s group
      user:
        name: dietpi
        groups: microk8s
        append: yes

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
      become_user: dietpi
