#!/bin/sh
echo "AUTO_SETUP_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFUZm7GJiVfgpK13RIG8CQbd3uaZpeoxHhQJveMI62Wf nick@pi.local" >> /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_KEYBOARD_LAYOUT=gb/AUTO_SETUP_KEYBOARD_LAYOUT=us/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s|AUTO_SETUP_TIMEZONE=Europe/London|AUTO_SETUP_TIMEZONE=Europe/Amsterdam|g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_WIFI_COUNTRY_CODE=NL/AUTO_SETUP_NET_WIFI_COUNTRY_CODE=NL/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_USESTATIC=0/AUTO_SETUP_NET_USESTATIC=1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_STATIC_IP=192.168.0.100/AUTO_SETUP_NET_STATIC_IP=192.168.107.10${1}/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_STATIC_GATEWAY=192.168.0.1/AUTO_SETUP_NET_STATIC_GATEWAY=192.168.107.1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_STATIC_DNS=9.9.9.9 149.112.112.112/AUTO_SETUP_NET_STATIC_DNS=192.168.107.1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_NET_HOSTNAME=DietPi/AUTO_SETUP_NET_HOSTNAME=neo${1}/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_SWAPFILE_SIZE=1/AUTO_SETUP_SWAPFILE_SIZE=0/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_HEADLESS=0/AUTO_SETUP_HEADLESS=1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_AUTOSTART_TARGET_INDEX=0/AUTO_SETUP_AUTOSTART_TARGET_INDEX=7/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_AUTOMATED=0/AUTO_SETUP_AUTOMATED=1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/AUTO_SETUP_GLOBAL_PASSWORD=dietpi/AUTO_SETUP_GLOBAL_PASSWORD=neo${1}/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/CONFIG_CPU_DISABLE_TURBO=0/CONFIG_CPU_DISABLE_TURBO=1/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/CONFIG_CPU_GOVERNOR=schedutil/CONFIG_CPU_GOVERNOR=powersave/g" /media/nick/DIETPISETUP/dietpi.txt
sed -i "s/SOFTWARE_DISABLE_SSH_PASSWORD_LOGINS=0/SOFTWARE_DISABLE_SSH_PASSWORD_LOGINS=1/g" /media/nick/DIETPISETUP/dietpi.txt
