apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: redis
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: redis
type: Opaque
data:
  postgres-password: cmVkaXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: redis
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: docker.io/library/postgres:12-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
            - name: POSTGRES_USER
              value: authentik
            - name: POSTGRES_DB
              value: authentik
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:alpine
          command:
            - "redis-server"
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  ports:
    - port: 6379
      targetPort: 6380
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-node
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6380
    nodePort: 30379
  selector:
    app: redis